apiVersion: batch/v1
kind: Job
metadata:
  name: research-job-template  # This will be dynamically replaced
  labels:
    app: open-deep-research
spec:
  ttlSecondsAfterFinished: 300  # Delete job 5 minutes after completion
  template:
    metadata:
      labels:
        app: open-deep-research
    spec:
      containers:
      - name: open-deep-research
        image: ghcr.io/maccam912/open_deep_research_telegram_k8s/open-deep-research:latest
        args: ["QUERY_PLACEHOLDER"]  # This will be dynamically replaced
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: research-api-secrets
              key: hf-token
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: research-api-secrets
              key: openrouter-api-key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        # If needed, you can mount volumes here
        # volumeMounts:
        # - name: research-cache
        #   mountPath: /app/open_deep_research/cache
      # volumes:
      # - name: research-cache
      #   emptyDir: {}
      restartPolicy: Never
  backoffLimit: 1