apiVersion: v1
kind: Secret
metadata:
  name: research-api-secrets
type: Opaque
data:
  # You need to replace these with your actual encoded tokens
  # Use: echo -n 'your-token' | base64
  hf-token: YOUR_BASE64_ENCODED_HF_TOKEN_HERE
  openrouter-api-key: YOUR_BASE64_ENCODED_OPENROUTER_API_KEY_HERE