apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegram-bot
  namespace: opendeepresearch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: opendeepresearch
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telegram-bot-job-manager
  namespace: opendeepresearch
subjects:
- kind: ServiceAccount
  name: telegram-bot
  namespace: opendeepresearch
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  labels:
    app: telegram-bot
  namespace: opendeepresearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      serviceAccountName: telegram-bot
      containers:
      - name: telegram-bot
        image: ghcr.io/maccam912/open_deep_research_telegram_k8s/telegram-bot:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'if [ $(( $(date +%s) - $(stat -c %Y /proc/1) )) -gt 1800 ]; then exit 1; fi'
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secrets
              key: bot-token