name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  MAIN_IMAGE_NAME: maccam912/open_deep_research_telegram_k8s/open-deep-research
  TELEGRAM_IMAGE_NAME: maccam912/open_deep_research_telegram_k8s/telegram-bot

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for main image
        id: meta-main
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.MAIN_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push main image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}

      - name: Extract metadata (tags, labels) for telegram bot
        id: meta-telegram
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.TELEGRAM_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push telegram bot image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.telegram
          push: true
          tags: ${{ steps.meta-telegram.outputs.tags }}
          labels: ${{ steps.meta-telegram.outputs.labels }}